use_frameworks!

platform :ios, '9.0'

target 'GMLFPSManager_Example' do
  pod 'GMLFPSManager', :path => '../'

  target 'GMLFPSManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
